import type { ArticleDto } from '@/components/article-card';

// 실제 다이제스트에서 추출한 시드 데이터 (API 미가동 시 시각 검증용)
export const MOCK_ARTICLES: ArticleDto[] = [
  {
    id: 'm1',
    title: 'Anthropic, Claude Opus 4.8 출시',
    url: 'https://www.anthropic.com/news',
    summaryOneLine: 'Anthropic 이 코딩 정확도가 개선되고 dynamic workflow 도구가 추가된 Opus 4.8 을 발표.',
    summaryThreeLine: null,
    publishedAt: '2026-05-29T08:30:00Z',
    tags: ['AI', 'LLM', 'Anthropic'],
    imageUrl: null,
    source: { name: 'Anthropic', provider: 'anthropic' },
  },
  {
    id: 'm2',
    title: 'Claude Code 를 일상 도구로 쓰기: Claude.md, Skills, Subagents, Plugins, MCP',
    url: 'https://news.hada.io',
    summaryOneLine: 'Claude Code 의 메타 도구 5종 활용 경험 정리.',
    summaryThreeLine: null,
    publishedAt: '2026-05-29T07:15:00Z',
    tags: ['Claude', '워크플로우', 'AI'],
    imageUrl: null,
    source: { name: 'GeekNews', provider: 'geeknews' },
  },
  {
    id: 'm3',
    title: 'Anthropic 이 65억 달러 투자 유치, 1조 달러 가치 평가 IPO 임박',
    url: 'https://techcrunch.com',
    summaryOneLine: 'Anthropic 이 사상 최대 규모 라운드를 마감하며 IPO 임박 신호.',
    summaryThreeLine: null,
    publishedAt: '2026-05-29T06:45:00Z',
    tags: ['Anthropic', '투자', 'IPO'],
    imageUrl: null,
    source: { name: 'TechCrunch', provider: 'techcrunch' },
  },
  {
    id: 'm4',
    title: 'The Orchestration Tax',
    url: 'https://news.hada.io',
    summaryOneLine: '에이전트 오케스트레이션 비용이 LLM 호출 비용을 압도하기 시작함.',
    summaryThreeLine: null,
    publishedAt: '2026-05-29T05:20:00Z',
    tags: ['에이전트', 'LLM', '아키텍처'],
    imageUrl: null,
    source: { name: 'GeekNews', provider: 'geeknews' },
  },
  {
    id: 'm5',
    title: '다음 토큰 예측은 우리에게 어떤 의미를 갖는 것일까?',
    url: 'https://news.hada.io',
    summaryOneLine: '언어 모델의 본질 다음 토큰 예측이 인지에 갖는 함의 분석.',
    summaryThreeLine: null,
    publishedAt: '2026-05-29T04:10:00Z',
    tags: ['LLM', '인지과학'],
    imageUrl: null,
    source: { name: 'GeekNews', provider: 'geeknews' },
  },
  {
    id: 'm6',
    title: 'Stack Overflow 의 포럼은 죽었지만 회사는 여전히 버티고 있음',
    url: 'https://news.hada.io',
    summaryOneLine: 'Q&A 트래픽이 70% 줄어든 Stack Overflow 의 비즈니스 전환 상황.',
    summaryThreeLine: null,
    publishedAt: '2026-05-29T03:30:00Z',
    tags: ['커뮤니티', '비즈니스'],
    imageUrl: null,
    source: { name: 'GeekNews', provider: 'geeknews' },
  },
  {
    id: 'm7',
    title: 'Anthropic 의 SpaceX 임대 계약은 얼마나 되나, 의견 분분',
    url: 'https://techcrunch.com',
    summaryOneLine: 'Anthropic 이 컴퓨트 확보를 위해 SpaceX 와 맺은 임대 계약 추정.',
    summaryThreeLine: null,
    publishedAt: '2026-05-29T02:50:00Z',
    tags: ['Anthropic', 'GPU', '인프라'],
    imageUrl: null,
    source: { name: 'TechCrunch', provider: 'techcrunch' },
  },
  {
    id: 'm8',
    title: 'I paid for Cursor and Claude Code for 6 months. Here\'s the one to keep.',
    url: 'https://dev.to',
    summaryOneLine: 'Cursor 와 Claude Code 를 6개월 병행 사용한 후 선택한 도구 후기.',
    summaryThreeLine: null,
    publishedAt: '2026-05-28T22:00:00Z',
    tags: ['Cursor', 'Claude', 'IDE'],
    imageUrl: null,
    source: { name: 'dev.to', provider: 'devto' },
  },
  {
    id: 'm9',
    title: 'Sneak peek at new Siri app reveals Apple\'s plans to take on ChatGPT',
    url: 'https://techcrunch.com',
    summaryOneLine: '새 Siri 앱 사전 유출, ChatGPT 대응 위한 Apple 의 전략 윤곽.',
    summaryThreeLine: null,
    publishedAt: '2026-05-28T19:30:00Z',
    tags: ['Apple', 'Siri', 'AI 어시스턴트'],
    imageUrl: null,
    source: { name: 'TechCrunch', provider: 'techcrunch' },
  },
  {
    id: 'm10',
    title: 'Rust 에서 Ruby 로',
    url: 'https://news.hada.io',
    summaryOneLine: 'Rust 에서 Ruby 로 전환한 팀의 의사결정 배경과 트레이드오프.',
    summaryThreeLine: null,
    publishedAt: '2026-05-28T17:00:00Z',
    tags: ['Rust', 'Ruby', '언어 선택'],
    imageUrl: null,
    source: { name: 'GeekNews', provider: 'geeknews' },
  },
  {
    id: 'm11',
    title: 'AI Is Not Killing Developer Jobs — But It Is Killing Certain Developer Habits',
    url: 'https://dev.to',
    summaryOneLine: 'AI 는 개발자 일자리를 줄이지 않지만 특정 습관을 사라지게 한다.',
    summaryThreeLine: null,
    publishedAt: '2026-05-28T15:00:00Z',
    tags: ['AI', '커리어'],
    imageUrl: null,
    source: { name: 'dev.to', provider: 'devto' },
  },
  {
    id: 'm12',
    title: 'YouTube 가 AI 생성 동영상에 자동으로 라벨을 붙일 예정',
    url: 'https://news.hada.io',
    summaryOneLine: 'YouTube 가 AI 생성 콘텐츠 식별 자동 라벨링 정책을 발표.',
    summaryThreeLine: null,
    publishedAt: '2026-05-28T12:30:00Z',
    tags: ['YouTube', 'AI 정책'],
    imageUrl: null,
    source: { name: 'GeekNews', provider: 'geeknews' },
  },
  {
    id: 'm13',
    title: 'Why Your Data Lineage Is Still a Spreadsheet (and How to Fix It in 5 Minutes)',
    url: 'https://dev.to',
    summaryOneLine: '데이터 라인리지를 스프레드시트로 관리하는 함정과 5분 해결책.',
    summaryThreeLine: null,
    publishedAt: '2026-05-28T10:00:00Z',
    tags: ['데이터', '엔지니어링'],
    imageUrl: null,
    source: { name: 'dev.to', provider: 'devto' },
  },
  {
    id: 'm14',
    title: 'Last.fm 이 이제 독립 운영됨',
    url: 'https://news.hada.io',
    summaryOneLine: 'CBS 인수 18년 만에 Last.fm 이 독립 회사로 분리.',
    summaryThreeLine: null,
    publishedAt: '2026-05-28T08:00:00Z',
    tags: ['음악', '서비스'],
    imageUrl: null,
    source: { name: 'GeekNews', provider: 'geeknews' },
  },
  {
    id: 'm15',
    title: 'Anthropic 과 OpenAI 가 제품-시장 적합성을 찾았다고 생각한다',
    url: 'https://news.hada.io',
    summaryOneLine: 'AI 양강의 매출 성장 곡선과 사용 패턴에서 PMF 신호 분석.',
    summaryThreeLine: null,
    publishedAt: '2026-05-28T06:00:00Z',
    tags: ['Anthropic', 'OpenAI', 'PMF'],
    imageUrl: null,
    source: { name: 'GeekNews', provider: 'geeknews' },
  },
  {
    id: 'm16',
    title: '사내 AI Championship 2등 하다 (feat. 200만원)',
    url: 'https://news.hada.io',
    summaryOneLine: '사내 AI 챔피언십 2등 후기와 사용한 프롬프트 패턴 공유.',
    summaryThreeLine: null,
    publishedAt: '2026-05-28T04:00:00Z',
    tags: ['AI', '경험기'],
    imageUrl: null,
    source: { name: 'GeekNews', provider: 'geeknews' },
  },
  {
    id: 'm17',
    title: 'Asana acquires no-code agent-builder StackAI',
    url: 'https://techcrunch.com',
    summaryOneLine: 'Asana 가 노코드 에이전트 빌더 StackAI 를 인수.',
    summaryThreeLine: null,
    publishedAt: '2026-05-27T20:00:00Z',
    tags: ['에이전트', '노코드', '인수'],
    imageUrl: null,
    source: { name: 'TechCrunch', provider: 'techcrunch' },
  },
  {
    id: 'm18',
    title: 'Show GN: Devflow Native - AI 코딩 에이전트 작업 흐름을 repo 안에 남기는 CLI',
    url: 'https://news.hada.io',
    summaryOneLine: 'AI 코딩 에이전트의 작업 흐름을 repo 메타데이터로 남기는 CLI 공유.',
    summaryThreeLine: null,
    publishedAt: '2026-05-27T18:00:00Z',
    tags: ['CLI', '에이전트', '개발도구'],
    imageUrl: null,
    source: { name: 'GeekNews', provider: 'geeknews' },
  },
  {
    id: 'm19',
    title: 'How to apply to Startup Battlefield 2026',
    url: 'https://techcrunch.com',
    summaryOneLine: 'Startup Battlefield 2026 지원 가이드와 6월 8일 마감 일정.',
    summaryThreeLine: null,
    publishedAt: '2026-05-27T15:00:00Z',
    tags: ['스타트업', '컨퍼런스'],
    imageUrl: null,
    source: { name: 'TechCrunch', provider: 'techcrunch' },
  },
  {
    id: 'm20',
    title: 'Best AI for Code: Top 4 Tools Tested and Ranked',
    url: 'https://dev.to',
    summaryOneLine: 'Cursor, Claude Code, Copilot, Codex 4종 코드 도구 비교 평가.',
    summaryThreeLine: null,
    publishedAt: '2026-05-27T12:00:00Z',
    tags: ['AI 코딩', '비교'],
    imageUrl: null,
    source: { name: 'dev.to', provider: 'devto' },
  },
  {
    id: 'm21',
    title: 'AI 와 대화하는 데 지쳤어요',
    url: 'https://news.hada.io',
    summaryOneLine: 'AI 의사소통 피로 현상과 사용자 번아웃 분석.',
    summaryThreeLine: null,
    publishedAt: '2026-05-27T09:00:00Z',
    tags: ['AI 윤리', 'UX'],
    imageUrl: null,
    source: { name: 'GeekNews', provider: 'geeknews' },
  },
  {
    id: 'm22',
    title: 'Robinhood Agentic Trading',
    url: 'https://producthunt.com',
    summaryOneLine: 'Robinhood 가 에이전트 기반 자동 트레이딩 기능을 공개.',
    summaryThreeLine: null,
    publishedAt: '2026-05-27T07:00:00Z',
    tags: ['핀테크', '에이전트'],
    imageUrl: null,
    source: { name: 'Product Hunt', provider: 'producthunt' },
  },
  {
    id: 'm23',
    title: 'Apple 과 Google 은 푸시 알림에 무엇을 하고 있나',
    url: 'https://news.hada.io',
    summaryOneLine: 'iOS 와 Android 의 푸시 알림 정책 변화와 영향 분석.',
    summaryThreeLine: null,
    publishedAt: '2026-05-27T05:00:00Z',
    tags: ['Apple', 'Google', '플랫폼'],
    imageUrl: null,
    source: { name: 'GeekNews', provider: 'geeknews' },
  },
  {
    id: 'm24',
    title: 'Atom 고갈은 실수가 아니다. 우리 CVE 의 3분의 1이다',
    url: 'https://news.hada.io',
    summaryOneLine: '메모리 관리 버그가 전체 CVE 의 33% 를 차지한다는 분석.',
    summaryThreeLine: null,
    publishedAt: '2026-05-27T03:00:00Z',
    tags: ['보안', '메모리'],
    imageUrl: null,
    source: { name: 'GeekNews', provider: 'geeknews' },
  },
  {
    id: 'm25',
    title: 'AI Hallucinations Are Not a Bug. They Are the Architecture.',
    url: 'https://dev.to',
    summaryOneLine: 'LLM 환각은 버그가 아닌 구조적 결과라는 관점과 대응 패턴.',
    summaryThreeLine: null,
    publishedAt: '2026-05-26T21:00:00Z',
    tags: ['LLM', '환각', '아키텍처'],
    imageUrl: null,
    source: { name: 'dev.to', provider: 'devto' },
  },
  {
    id: 'm26',
    title: 'Neovim 에 보내는 러브레터',
    url: 'https://news.hada.io',
    summaryOneLine: '5년차 Neovim 사용자의 에디터 철학 에세이.',
    summaryThreeLine: null,
    publishedAt: '2026-05-26T18:00:00Z',
    tags: ['에디터', '개발자'],
    imageUrl: null,
    source: { name: 'GeekNews', provider: 'geeknews' },
  },
  {
    id: 'm27',
    title: 'Waymo 의 새 로보택시는 중국제, 수익 위해 만들어졌고 이제 승객 모집 중',
    url: 'https://techcrunch.com',
    summaryOneLine: 'Waymo 가 중국산 6세대 로보택시로 수익성 개선에 본격 진입.',
    summaryThreeLine: null,
    publishedAt: '2026-05-26T15:00:00Z',
    tags: ['자율주행', 'Waymo'],
    imageUrl: null,
    source: { name: 'TechCrunch', provider: 'techcrunch' },
  },
  {
    id: 'm28',
    title: 'Bluesky 가 X Articles 에 대응해 장문 콘텐츠 도입',
    url: 'https://techcrunch.com',
    summaryOneLine: 'Bluesky 가 X 의 Articles 기능에 대응해 장문 게시 기능을 출시.',
    summaryThreeLine: null,
    publishedAt: '2026-05-26T12:00:00Z',
    tags: ['SNS', 'Bluesky'],
    imageUrl: null,
    source: { name: 'TechCrunch', provider: 'techcrunch' },
  },
  {
    id: 'm29',
    title: '4K 에서 SimCity 3K 실행하기 (2025)',
    url: 'https://news.hada.io',
    summaryOneLine: '2000년대 클래식 게임 SimCity 3K 를 4K 환경에서 구동한 기록.',
    summaryThreeLine: null,
    publishedAt: '2026-05-26T09:00:00Z',
    tags: ['게임', '레트로'],
    imageUrl: null,
    source: { name: 'GeekNews', provider: 'geeknews' },
  },
  {
    id: 'm30',
    title: '인류의 모든 요리를 2메가바이트로 압축하기',
    url: 'https://news.hada.io',
    summaryOneLine: '모든 요리 레시피를 2MB 압축으로 표현하는 데이터 구조 실험.',
    summaryThreeLine: null,
    publishedAt: '2026-05-26T06:00:00Z',
    tags: ['데이터', '실험'],
    imageUrl: null,
    source: { name: 'GeekNews', provider: 'geeknews' },
  },
];
